---
- name: Install nginx
  sudo: yes
  apt: name=nginx state=present

- name: Copy nginx configuration to available sites
  sudo: yes
  copy: src=test.conf dest=/etc/nginx/sites-available/repo_name

- name: Enable site
  sudo: yes
  file: src=/etc/nginx/sites-available/{{cookiecutter.repo_name}} dest=/etc/nginx/sites-enabled/{{cookiecutter.repo_name}} state=link

- name: Remove default site
  sudo: yes
  file: path=/etc/nginx/sites-enabled/default state=absent
  notify:
    - Restart nginx
