---
- name: Create database
  sudo: yes
  sudo_user: postgres
  postgresql_db: name={{cookiecutter.repo_name}} state=present

- name: Create database user
  sudo: yes
  sudo_user: postgres
  postgresql_user: name=vagrant role_attr_flags=CREATEDB state=present

- name: Perform migrations
  django_manage: app_path=/vagrant/{{cookiecutter.repo_name}} command=migrate

- name: Clear existing staticfiles dir
  file: path=/vagrant/staticfiles state=absent

- name: Symlink static files to staticfiles dir
  command: python /vagrant/{{cookiecutter.repo_name}}/manage.py collectstatic --noinput -l -i sass

