---
- name: Create database
  sudo: yes
  sudo_user: postgres
  postgresql_db: name={{cookiecutter.repo_name}}

- name: Create database user
  sudo: yes
  sudo_user: postgres
  postgresql_user: db={{cookiecutter.repo_name}} name=vagrant

- name: Sync DB
  django_manage: app_path=/vagrant/{{cookiecutter.repo_name}} command=syncdb

- name: Perform migrations
  django_manage: app_path=/vagrant/{{cookiecutter.repo_name}} command=migrate

- name: Clear existing staticfiles dir
  file: path=/vagrant/staticfiles state=absent

- name: Symlink static files to staticfiles dir
  command: python /vagrant/{{cookiecutter.repo_name}}/manage.py collectstatic --noinput -l -i sass

